// examples/sveltekit-live-avatars/src/LiveAvatars.svelte
<script>
  import { useOthers, useSelf } from "./lib-liveblocks";
  import Avatar from "$lib/Avatar.svelte";

  /**
   * The main Liveblocks code for the example.
   * Check in src/routes/index.svelte to see the setup code.
   *
   * The two hooks below work similarly to the `liveblocks-react` library
   * https://liveblocks.io/docs/api-reference/liveblocks-react
   * More info inside src/lib-liveblocks
   */

  let users = useOthers();
  let currentUser = useSelf();
  $: hasMoreUsers = $users ? [...$users].length > 3 : false;
</script>

<main>
  <div class="avatars">

    <!-- Show the first 3 users avatars -->
    {#if $users}
      {#each [...$users].slice(0, 3) as { connectionId, info } (connectionId)}
        <Avatar picture={info?.picture} name={info?.name} />
      {/each}
    {/if}

    <!-- Show the amount of people online past the third user -->
    {#if hasMoreUsers}
      <div class="more">+ {[...$users]?.length - 3}</div>
    {/if}

    <!-- Show the current user's avatar-->
    {#if $currentUser}
      <div class="current_user_container">
        <Avatar picture={$currentUser.info?.picture} name={$currentUser.info?.name} />
      </div>
    {/if}

  </div>
</main>

<style>
  main {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    user-select: none;
  }

  .avatars {
    display: flex;
    flex-direction: row;
    padding-left: 0.75rem;
  }

  .current_user_container {
    position: relative;
    margin-left: 2rem;
  }

  .more {
    border-width: 4px;
    border-radius: 9999px;
    border-color: white;
    background-color: #9ca3af;
    min-width: 56px;
    width: 56px;
    height: 56px;
    margin-left: -0.75rem;
    display: flex;
    justify-content: center;
    align-items: center;
    color: white;
  }
</style>

// examples/vuejs-live-avatars/src/components/LiveAvatars.vue
<script lang="ts" setup>
import { onUnmounted, ref } from "vue";
import Avatar from "@/components/Avatar.vue";
import type { TypedRoom } from "@/liveblocks.config";

const { room } = defineProps<{
  room: TypedRoom;
}>();

// Get initial values for presence and others
const currentUser = ref(room.getPresence());
const others = ref(room.getOthers());

// Subscribe to further changes
const unsubscribeMyPresence = room.subscribe("my-presence", (newPresence) => {
  currentUser.value = newPresence;
});

const unsubscribeOthers = room.subscribe("others", (newOthers) => {
  others.value = newOthers;
});

// Unsubscribe when unmounting
onUnmounted(() => {
  unsubscribeMyPresence();
  unsubscribeOthers();
});
</script>

<template>
  <main class="main">
    <div class="avatars">
      <Avatar
        v-for="{ presence, connectionId } in others.slice(0, 3)"
        v-bind:key="connectionId"
        v-bind:name="presence.name"
        v-bind:picture="presence.picture"
      />

      <div v-if="others.length > 3" class="more">+{{ others.length - 3 }}</div>

      <div class="self">
        <Avatar
          v-if="currentUser"
          name="You"
          v-bind:picture="currentUser.picture"
        />
      </div>
    </div>
  </main>
</template>

<style scoped>
.main {
  height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
  user-select: none;
  overflow: hidden;
}

.avatars {
  display: flex;
  padding-left: 12px;
}

.self {
  position: relative;
  margin-left: 32px;
}

.self:first-child {
  margin-left: 0;
}

.more {
  border-width: 4px;
  border-radius: 9999px;
  border-color: white;
  background-color: #9ca3af;
  min-width: 56px;
  width: 56px;
  height: 56px;
  margin-left: -0.75rem;
  display: flex;
  z-index: 1;
  justify-content: center;
  align-items: center;
  color: white;
}
</style>
