// examples/solidjs-live-cursors/src/index.jsx
/* @refresh reload */
import { render } from "solid-js/web";
import { createClient } from "@liveblocks/client";
import App from "./App";
import "./index.css";

let PUBLIC_KEY = "pk_YOUR_PUBLIC_KEY";
let roomId = "solidjs-live-cursors";

overrideApiKeyAndRoomId();

if (!/^pk_(live|test)/.test(PUBLIC_KEY)) {
  console.warn(
    `Replace "${PUBLIC_KEY}" by your public key from https://liveblocks.io/dashboard/apikeys.\n` +
    `Learn more: https://github.com/liveblocks/liveblocks/tree/main/examples/solidjs-live-cursors#getting-started.`,
  );
}

const client = createClient({
  publicApiKey: PUBLIC_KEY,
});

const initialPresence = {
  cursor: null,
};

const room = client.enter(roomId, { initialPresence });

render(() => <App room={room} />, document.getElementById("root"));

/**
 * This function is used when deploying an example on liveblocks.io.
 * You can ignore it completely if you run the example locally.
 */
function overrideApiKeyAndRoomId() {
  const query = new URLSearchParams(window?.location?.search);
  const apiKey = query.get("apiKey");
  const roomIdSuffix = query.get("roomId");

  if (apiKey) {
    PUBLIC_KEY = apiKey;
  }

  if (roomIdSuffix) {
    roomId = `${roomId}-${roomIdSuffix}`;
  }
}

// examples/react-whiteboard/src/index.js
import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";
import { createClient } from "@liveblocks/client";
import { LiveblocksProvider, RoomProvider } from "@liveblocks/react";
import "./index.css";

/**
 * Replace by your public key from https://liveblocks.io/dashboard/apikeys.
 */
const PUBLIC_KEY = "pk_YOUR_PUBLIC_KEY";

if (!/^pk_(live|test)/.test(PUBLIC_KEY)) {
  console.warn(
    `Replace "${PUBLIC_KEY}" by your public key from https://liveblocks.io/dashboard/apikeys.\n` +
      `Learn more: https://github.com/liveblocks/liveblocks/tree/main/examples/react-whiteboard#getting-started.`
  );
}

const client = createClient({
  publicApiKey: PUBLIC_KEY,
});

const defaultRoomId = "react-whiteboard";

function Page() {
  const [roomId, setRoomId] = useState(defaultRoomId);

  /**
   * Add a suffix to the room ID using a query parameter.
   * Used for coordinating rooms from outside (e.g. https://liveblocks.io/examples).
   *
   * http://localhost:3000/?room=1234 → react-whiteboard-1234
   */
  useEffect(() => {
    const roomSuffix = new URLSearchParams(window?.location?.search).get(
      "room"
    );

    if (roomSuffix) {
      setRoomId(`${defaultRoomId}-${roomSuffix}`);
    }
  }, []);

  return (
    <RoomProvider id={roomId}>
      <App />
    </RoomProvider>
  );
}

const root = ReactDOM.createRoot(document.getElementById("root"));

root.render(
  <React.StrictMode>
    <LiveblocksProvider client={client}>
      <Page />
    </LiveblocksProvider>
  </React.StrictMode>
);
