// examples/vuejs-live-cursors/src/components/Cursor.vue
<script lang="ts" setup>
interface Props {
  color: string;
  x: number;
  y: number;
}

const props = defineProps<Props>();
</script>

<template>
  <svg
    :style="{ transform: `translateX(${x}px) translateY(${y}px)` }"
    fill="none"
    height="36"
    viewBox="0 0 24 36"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      :style="{ fill: color }"
      d="M5.65376 12.3673H5.46026L5.31717 12.4976L0.500002 16.8829L0.500002 1.19841L11.7841 12.3673H5.65376Z"
    />
  </svg>
</template>

<style scoped>
svg {
  position: absolute;
  left: 0;
  top: 0;
}
</style>

// examples/nextjs-connection-status/components/Cursor.tsx
"use client";

import React from "react";

type Props = {
  color: string;
  x: number;
  y: number;
};

export default function Cursor({ color, x, y }: Props) {
  return (
    <svg
      style={{
        position: "absolute",
        left: 0,
        top: 0,
        transform: `translateX(${x}px) translateY(${y}px)`,
      }}
      width="24"
      height="36"
      viewBox="0 0 24 36"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        d="M5.65376 12.3673H5.46026L5.31717 12.4976L0.500002 16.8829L0.500002 1.19841L11.7841 12.3673H5.65376Z"
        fill={color}
      />
    </svg>
  );
}
