// examples/react-comments/src/main.tsx
import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";
import "./styles/globals.css";

let roomId = "react-comments";
overrideRoomId();

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <App roomId={roomId} />
  </React.StrictMode>
);

/**
 * This function is used when deploying an example on liveblocks.io.
 * You can ignore it completely if you run the example locally.
 */
function overrideRoomId() {
  const query = new URLSearchParams(window?.location?.search);
  const roomIdSuffix = query.get("roomId");

  if (roomIdSuffix) {
    roomId = `${roomId}-${roomIdSuffix}`;
  }
}

// examples/solidjs-live-cursors/src/index.tsx
/* @refresh reload */
import { render } from "solid-js/web";
import { type TypedRoom, client, PUBLIC_API_KEY } from "./liveblocks.config";
import App from "./App";
import "./index.css";

let PUBLIC_KEY = PUBLIC_API_KEY;
let roomId = "solidjs-live-cursors";

overrideApiKeyAndRoomId();

const initialPresence = {
  cursor: null,
};
const room = client.enter(roomId, { initialPresence }) as TypedRoom;

render(() => <App room={room} />, document.getElementById("root"));

/**
 * This function is used when deploying an example on liveblocks.io.
 * You can ignore it completely if you run the example locally.
 */
function overrideApiKeyAndRoomId() {
  const query = new URLSearchParams(window?.location?.search);
  const apiKey = query.get("apiKey");
  const roomIdSuffix = query.get("roomId");

  if (apiKey) {
    PUBLIC_KEY = apiKey;
  }

  if (roomIdSuffix) {
    roomId = `${roomId}-${roomIdSuffix}`;
  }
}
