// examples/nuxtjs-live-avatars/pages/live-avatars.vue
<template>
  <main class="flex justify-center items-center h-screen select-none">
    <GithubLink
      className="fixed top-8 right-8"
      href="https://github.com/liveblocks/liveblocks/tree/main/examples/nuxtjs-live-avatars"
    ></GithubLink>
    <div class="flex flex-row pl-3">
      <Avatar
        v-for="user in others"
        v-bind:key="user.connectionId"
        v-bind:picture="user.picture"
        v-bind:name="user.name"
      ></Avatar>

      <div class="relative ml-8">
        <Avatar
          v-if="currentUser"
          v-bind:picture="currentUser.info.picture"
          name="You"
        ></Avatar>
      </div>
    </div>
  </main>
</template>

<script>
import Vue from "vue";
import { createClient } from "@liveblocks/client";

const client = createClient({
  authEndpoint: "/api/auth"
});

const roomId = "nuxt-js-live-avatars";

export default Vue.extend({
  data: function() {
    return {
      others: [],
      currentUser: null
    };
  },
  mounted: function() {
    const room = client.enter(roomId);
    room.subscribe("others", this.onOthersChange);
    room.subscribe("connection", this.onConnectionChange);
    this._room = room;
  },
  destroyed: function() {
    this._room.unsubscribe("others", this.onOthersChange);
    this._room.unsubscribe("connection", this.onConnectionChange);
    client.leave(roomId);
  },
  methods: {
    onOthersChange: function(others) {
      // The picture and name are comming from the authentication endpoint
      // See api.js for and https://liveblocks.io/docs/api-reference/liveblocks-node#authorize for more information
      this.others = others.map(user => ({
        connectionId: user.connectionId,
        picture: user.info?.picture,
        name: user.info?.name
      }));
    },
    onConnectionChange: function() {
      this.currentUser = this._room.getSelf();
    }
  }
});
</script>

// examples/nextjs-starter-typescript/components/LiveAvatars.tsx
import React from "react";
import { Avatar } from "./Avatar";
import { useOthers, useSelf } from "@liveblocks/react";

/**
 * This file shows how to add live avatars like you can see them at the top right of a Google Doc or a Figma file.
 * https://liveblocks.io/docs/examples/live-avatars
 *
 * The users picture and name are not set via the `useMyPresence` hook like the cursors.
 * They are set from the authentication endpoint.
 *
 * See pages/api/auth.ts and https://liveblocks.io/docs/api-reference/liveblocks-node#authorize for more information
 */

const MAX_OTHERS = 3;

const avatarProps = {
  style: { marginLeft: "-0.45rem" },
  size: 48,
  outlineWidth: 4,
  outlineColor: "white",
};

export default function LiveAvatars() {
  const users = useOthers().toArray();
  const currentUser = useSelf();
  const hasMoreUsers = users.length > MAX_OTHERS;

  return (
    <div
      style={{
        minHeight: avatarProps.size + "px",
        display: "flex",
        paddingLeft: "0.75rem",
        overflow: "hidden",
      }}
    >
        {hasMoreUsers ? (
          <Avatar
            key="count"
            variant="more"
            count={users.length - 3}
            {...avatarProps}
          />
        ) : null}

        {users
          .slice(0, MAX_OTHERS)
          .reverse()
          .map(({ connectionId, info }) => (
            <Avatar
              key={connectionId}
              picture={info?.picture}
              name={info?.name}
              color={info?.color}
              {...avatarProps}
            />
          ))}

        {currentUser ? (
          <Avatar
            key="you"
            picture={currentUser.info?.picture}
            name={currentUser.info?.name + " (you)"}
            color={currentUser.info?.color}
            {...avatarProps}
          />
        ) : null}
    </div>
  );
}
