// examples/nuxtjs-live-avatars/components/InlineCodeBlock.vue
<template>
    <pre
      class="relative inline-block font-mono bg-black shadow-thin-border-300 rounded-lg text-sm text-gray-200 p-2 pl-0"
      style="
        min-height: 36px;
        line-height: 1.5em;
      "
    >
      <code>{{code}}</code>
    </pre>
</template>

<script>
  export default {
    props: ["code"]
  }
</script>

// examples/nextjs-todo-list/components/InlineCodeBlock.tsx
export default function InlineCodeBlock({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <pre
      className="relative inline font-mono bg-black shadow-thin-border-300 rounded-lg my-4 text-sm text-gray-200 p-2"
      style={{
        minHeight: "36px",
        lineHeight: "1.5em",
      }}
    >
      <code>{children}</code>
    </pre>
  );
}
